import React, { useState, useEffect, useRef, useCallback } from "react";

/* ============================================================
   AI PROFILE ROASTER & HYPER
   Cyberpunk neon single-page app — roast or hype a social bio.
   ============================================================ */

/* ---------------- i18n ---------------- */

const LANGS = [
  { code: "en", label: "EN", name: "English" },
  { code: "sr", label: "SR/HR", name: "Srpski/Hrvatski" },
  { code: "de", label: "DE", name: "Deutsch" },
  { code: "zh", label: "中文", name: "中文" },
];

const UI = {
  en: {
    brand: "RoastMeAI",
    heroTitle: "AI Profile Roaster & Hyper",
    heroSub: "Paste your bio. Pick your poison. Let the machine judge you.",
    bioLabel: "Your bio / description",
    bioPlaceholder:
      "Paste your Instagram, TikTok or LinkedIn bio here... the more cringe, the better the material.",
    uploadLabel: "Or upload a profile screenshot",
    uploadHint: "PNG or JPG · analyzed locally, never uploaded anywhere",
    uploadReplace: "Replace image",
    analyzing: "Scanning pixels for personality...",
    analyzed: "Visual data captured",
    roastBtn: "ROAST ME",
    roastSub: "brutal honesty incoming",
    hypeBtn: "HYPE ME",
    hypeSub: "delusional confidence incoming",
    validationError: "Feed me some text or an image first. I can't roast a void.",
    generatingTitle: "Processing...",
    genSteps: [
      "Parsing bio syntax",
      "Cross-referencing internet subcultures",
      "Calibrating sarcasm levels",
      "Rendering verdict",
    ],
    outputRoastTitle: "THE VERDICT",
    outputHypeTitle: "THE HYPE",
    downloadBtn: "Download Card",
    shareBtn: "Share to Story",
    regenBtn: "Try Again",
    switchModeRoast: "Switch to Roast",
    switchModeHype: "Switch to Hype",
    downloadToast: "Card saved to your gallery ✦",
    shareToast: "Opening Instagram Story composer ✦",
    branding: "Generated by RoastMeAI.com",
    premiumTitle: "Premium Modes",
    premiumSub: "For when free savagery isn't enough",
    premiumModes: [
      {
        title: "Dating Profile Verdict",
        desc: "Would they swipe right? A brutal romantic audit.",
      },
      {
        title: "Career Self-Sabotage Analysis",
        desc: "The professional red flags in your own words.",
      },
      {
        title: "Nuclear Roast",
        desc: "No filter. No mercy. Therapy not included.",
      },
    ],
    unlockBtn: "Unlock for €2.99",
    premiumToast: "Premium launching soon — wishlist saved ✦",
    footer: "Not affiliated with any social platform. For entertainment only.",
    startOver: "Start Over",
  },
  sr: {
    brand: "RoastMeAI",
    heroTitle: "AI Roaster & Hype Profila",
    heroSub: "Nalepi svoj opis. Izaberi otrov. Neka te mašina presudi.",
    bioLabel: "Tvoj bio / opis",
    bioPlaceholder:
      "Nalepi svoj Instagram, TikTok ili LinkedIn opis ovde... što je više cringe, to je bolji materijal.",
    uploadLabel: "Ili otpremi screenshot profila",
    uploadHint: "PNG ili JPG · analiza je lokalna, nigde se ne šalje",
    uploadReplace: "Zameni sliku",
    analyzing: "Skeniram piksele u potrazi za ličnošću...",
    analyzed: "Vizuelni podaci uhvaćeni",
    roastBtn: "SPRŽI ME",
    roastSub: "stiže brutalna istina",
    hypeBtn: "NAHAJPUJ ME",
    hypeSub: "stiže neosnovano samopouzdanje",
    validationError: "Daj mi bar malo teksta ili sliku. Ne mogu da pržim prazninu.",
    generatingTitle: "Obrada u toku...",
    genSteps: [
      "Analiziram sintaksu bio-a",
      "Upoređujem sa internet supkulturama",
      "Kalibrišem nivo sarkazma",
      "Generišem presudu",
    ],
    outputRoastTitle: "PRESUDA",
    outputHypeTitle: "HAJP",
    downloadBtn: "Preuzmi karticu",
    shareBtn: "Podeli u Story",
    regenBtn: "Probaj ponovo",
    switchModeRoast: "Prebaci na Roast",
    switchModeHype: "Prebaci na Hype",
    downloadToast: "Kartica sačuvana u galeriji ✦",
    shareToast: "Otvaram Instagram Story editor ✦",
    branding: "Generisao RoastMeAI.com",
    premiumTitle: "Premium Modovi",
    premiumSub: "Za kad besplatna okrutnost nije dovoljna",
    premiumModes: [
      {
        title: "Presuda za Dating Profil",
        desc: "Da li bi te lajkovali? Brutalna romantična analiza.",
      },
      {
        title: "Analiza Karijernog Samosabotiranja",
        desc: "Profesionalne crvene zastave u tvojim rečima.",
      },
      {
        title: "Nuklearni Roast",
        desc: "Bez filtera. Bez milosti. Terapija nije uključena.",
      },
    ],
    unlockBtn: "Otključaj za €2.99",
    premiumToast: "Premium uskoro stiže — dodato na listu želja ✦",
    footer: "Nije povezano ni sa jednom društvenom mrežom. Samo za zabavu.",
    startOver: "Počni ispočetka",
  },
  de: {
    brand: "RoastMeAI",
    heroTitle: "KI Profil-Roaster & Hyper",
    heroSub: "Füg deine Bio ein. Wähl dein Gift. Lass die Maschine urteilen.",
    bioLabel: "Deine Bio / Beschreibung",
    bioPlaceholder:
      "Füg hier deine Instagram-, TikTok- oder LinkedIn-Bio ein... je peinlicher, desto besser das Material.",
    uploadLabel: "Oder lade einen Profil-Screenshot hoch",
    uploadHint: "PNG oder JPG · Analyse erfolgt lokal, wird nirgends hochgeladen",
    uploadReplace: "Bild ersetzen",
    analyzing: "Scanne Pixel nach Persönlichkeit...",
    analyzed: "Visuelle Daten erfasst",
    roastBtn: "ROAST MICH",
    roastSub: "brutale Ehrlichkeit folgt",
    hypeBtn: "HYPE MICH",
    hypeSub: "grenzenloses Selbstvertrauen folgt",
    validationError: "Gib mir Text oder ein Bild. Ich kann keine Leere rösten.",
    generatingTitle: "Verarbeitung läuft...",
    genSteps: [
      "Analysiere Bio-Syntax",
      "Gleiche mit Internet-Subkulturen ab",
      "Kalibriere Sarkasmus-Level",
      "Erstelle Urteil",
    ],
    outputRoastTitle: "DAS URTEIL",
    outputHypeTitle: "DER HYPE",
    downloadBtn: "Karte herunterladen",
    shareBtn: "In Story teilen",
    regenBtn: "Nochmal versuchen",
    switchModeRoast: "Zu Roast wechseln",
    switchModeHype: "Zu Hype wechseln",
    downloadToast: "Karte in der Galerie gespeichert ✦",
    shareToast: "Instagram-Story-Editor wird geöffnet ✦",
    branding: "Erstellt von RoastMeAI.com",
    premiumTitle: "Premium-Modi",
    premiumSub: "Wenn kostenlose Grausamkeit nicht reicht",
    premiumModes: [
      {
        title: "Dating-Profil-Urteil",
        desc: "Würde man nach rechts swipen? Ein brutales Liebes-Audit.",
      },
      {
        title: "Karriere-Selbstsabotage-Analyse",
        desc: "Die beruflichen Warnsignale in deinen eigenen Worten.",
      },
      {
        title: "Nuklearer Roast",
        desc: "Kein Filter. Keine Gnade. Therapie nicht inbegriffen.",
      },
    ],
    unlockBtn: "Freischalten für €2,99",
    premiumToast: "Premium startet bald — Wunschliste gespeichert ✦",
    footer: "Keine Partnerschaft mit sozialen Plattformen. Nur zur Unterhaltung.",
    startOver: "Neu starten",
  },
  zh: {
    brand: "RoastMeAI",
    heroTitle: "AI 个人资料吐槽 & 吹捧机",
    heroSub: "粘贴你的简介，选择你的毒药，让机器来评判你。",
    bioLabel: "你的简介 / 描述",
    bioPlaceholder:
      "粘贴你的 Instagram、TikTok 或 LinkedIn 简介...越尴尬，素材越好。",
    uploadLabel: "或上传个人资料截图",
    uploadHint: "PNG 或 JPG · 本地分析，绝不上传",
    uploadReplace: "更换图片",
    analyzing: "正在扫描像素以分析人格...",
    analyzed: "视觉数据已捕获",
    roastBtn: "吐槽我",
    roastSub: "残酷真相即将到来",
    hypeBtn: "吹捧我",
    hypeSub: "离谱自信即将到来",
    validationError: "先给我一些文字或图片，我没法吐槽一片空白。",
    generatingTitle: "处理中...",
    genSteps: [
      "解析简介语法",
      "对比网络亚文化数据库",
      "校准讽刺等级",
      "生成最终评判",
    ],
    outputRoastTitle: "最终评判",
    outputHypeTitle: "吹捧结果",
    downloadBtn: "下载卡片",
    shareBtn: "分享到 Story",
    regenBtn: "再试一次",
    switchModeRoast: "切换到吐槽",
    switchModeHype: "切换到吹捧",
    downloadToast: "卡片已保存到相册 ✦",
    shareToast: "正在打开 Instagram Story 编辑器 ✦",
    branding: "由 RoastMeAI.com 生成",
    premiumTitle: "高级模式",
    premiumSub: "当免费的毒舌还不够狠的时候",
    premiumModes: [
      {
        title: "约会资料终审",
        desc: "他们会右滑吗？一次残酷的恋爱审查。",
      },
      {
        title: "职场自毁行为分析",
        desc: "藏在你自己文字里的职业危险信号。",
      },
      {
        title: "核弹级吐槽",
        desc: "无过滤，无怜悯，不含心理咨询。",
      },
    ],
    unlockBtn: "解锁 €2.99",
    premiumToast: "高级功能即将上线，已加入愿望单 ✦",
    footer: "与任何社交平台无关，仅供娱乐。",
    startOver: "重新开始",
  },
};

/* ---------------- Roast / Hype content banks ---------------- */

const CONTENT = {
  en: {
    roastOpen: [
      "Okay, I read this. I have questions.",
      "Alright, sit down. This is going to hurt a little.",
      "I ran the numbers. The numbers are not kind.",
    ],
    roastLines: [
      "This bio reads like it was written by committee, and the committee quit halfway through.",
      "You've got {hashtags} hashtags in there — at this point it's not a bio, it's a ransom note to the algorithm.",
      "There's a strong 'main character energy' vibe here, but the supporting cast left the chat.",
      "{words} words and somehow zero information about who you actually are. Impressive, honestly.",
      "The emoji count ({emoji}) suggests you were charged by the letter and decided to cut costs elsewhere.",
      "This is giving 'linktree in bio' energy before you even got to the linktree.",
      "Somewhere a marketing intern is proud of this and I need you to sit with that.",
      "It's not bad, it's just... aggressively fine. Like a hotel lobby.",
    ],
    roastClose: [
      "Anyway, delete and start over — I say this with love, sort of.",
      "Verdict: needs a rewrite, a therapist, or both.",
      "10/10 for confidence, 3/10 for content. Balance it out.",
    ],
    hypeOpen: [
      "Buckle up, because I am about to be unreasonably kind.",
      "I read this and honestly? I stood up out of respect.",
      "This is not a bio. This is a manifesto and I am obsessed.",
    ],
    hypeLines: [
      "The way you structured {words} words is genuinely Pulitzer-committee behavior.",
      "{hashtags} hashtags and every single one is doing Olympic-level heavy lifting for the algorithm.",
      "This bio has main character energy and honestly the algorithm should be paying YOU.",
      "{emoji} emojis used with the precision of a Michelin-starred chef plating a dish.",
      "Every brand on earth is currently drafting a partnership email in your honor.",
      "Historians will study this bio the way they study the Rosetta Stone.",
      "You didn't write a profile, you wrote a personality the rest of us are still catching up to.",
      "Honestly this belongs in a museum, behind glass, with a small respectful plaque.",
    ],
    hypeClose: [
      "In conclusion: iconic, legendary, unbothered, moisturized in every sense of the word.",
      "Verdict: certified main character. The rest of us are NPCs.",
      "10/10, no notes, please never change a single word.",
    ],
    imageNote: "Visual analysis added extra context to this reading.",
  },
  sr: {
    roastOpen: [
      "Okej, pročitao/la sam ovo. Imam pitanja.",
      "Dobro, sedi. Ovo će malo da zaboli.",
      "Izračunao/la sam brojke. Brojke nisu nežne.",
    ],
    roastLines: [
      "Ovaj bio zvuči kao da ga je pisao ceo tim, pa je tim odustao na pola puta.",
      "Imaš {hashtags} hashtagova ovde — u ovom trenutku to više nije bio, to je otkupno pismo algoritmu.",
      "Ovde jako 'glavni lik' energija, ali sporedna ekipa je izašla iz razgovora.",
      "{words} reči i nekako nula informacija o tome ko si zapravo. Iskreno, impresivno.",
      "Broj emotikona ({emoji}) sugeriše da si plaćao/la po slovu pa si štedeo/la negde drugde.",
      "Ovo daje 'linktree u bio-u' vibe pre nego što si uopšte stigao/la do linktree-a.",
      "Negde je jedan marketing pripravnik ponosan na ovo i moraš to da preživiš.",
      "Nije loše, samo je... agresivno okej. Kao lobi hotela srednje kategorije.",
    ],
    roastClose: [
      "U svakom slučaju, obriši i počni ispočetka — kažem ovo iz ljubavi, otprilike.",
      "Presuda: treba prepravka, terapeut, ili oboje.",
      "10/10 za samopouzdanje, 3/10 za sadržaj. Izbalansiraj to.",
    ],
    hypeOpen: [
      "Pripremi se, jer ću sad biti nerazumno drag/a.",
      "Pročitao/la sam ovo i iskreno? Ustao/la sam iz poštovanja.",
      "Ovo nije bio. Ovo je manifest i ja sam opsednut/a.",
    ],
    hypeLines: [
      "Način na koji si strukturirao/la {words} reči je ozbiljno na nivou Nobelove nagrade za književnost.",
      "{hashtags} hashtagova i svaki od njih nosi olimpijski teret za algoritam.",
      "Ovaj bio ima energiju glavnog lika i iskreno, algoritam bi trebalo da plaća TEBI.",
      "{emoji} emotikona korišćeno sa preciznošću Michelin kuvara koji servira jelo.",
      "Svaki brend na planeti trenutno piše mejl za saradnju u tvoju čast.",
      "Istoričari će proučavati ovaj bio kao što proučavaju Vinčansko pismo.",
      "Nisi napisao/la profil, napisao/la si ličnost koju mi ostali tek sad sustižemo.",
      "Iskreno, ovo pripada muzeju, iza stakla, sa malom poštovanom pločicom.",
    ],
    hypeClose: [
      "Zaključak: ikona, legenda, nedodirljiv/a, sređen/a u svakom smislu te reči.",
      "Presuda: zvanično glavni lik. Mi ostali smo NPC-jevi.",
      "10/10, bez primedbi, molim te nikad ne menjaj nijednu reč.",
    ],
    imageNote: "Vizuelna analiza je dodala dodatni kontekst ovoj presudi.",
  },
  de: {
    roastOpen: [
      "Okay, ich hab das gelesen. Ich habe Fragen.",
      "Gut, setz dich hin. Das wird ein bisschen wehtun.",
      "Ich hab die Zahlen durchgerechnet. Die Zahlen sind nicht nett.",
    ],
    roastLines: [
      "Diese Bio liest sich, als hätte ein ganzes Komitee sie geschrieben — und das Komitee hat auf halbem Weg aufgegeben.",
      "Du hast {hashtags} Hashtags drin — das ist keine Bio mehr, das ist ein Lösegeldbrief an den Algorithmus.",
      "Hier ist starke 'Hauptfigur-Energie' zu spüren, aber die Nebendarsteller haben den Chat verlassen.",
      "{words} Wörter und trotzdem null Information darüber, wer du eigentlich bist. Ehrlich gesagt beeindruckend.",
      "Die Emoji-Anzahl ({emoji}) legt nahe, dass du pro Buchstabe bezahlt hast und woanders gespart hast.",
      "Das hat schon 'Linktree in der Bio'-Energie, bevor du überhaupt beim Linktree bist.",
      "Irgendwo ist ein Marketing-Praktikant stolz darauf, und du musst da jetzt durch.",
      "Es ist nicht schlecht, es ist nur... aggressiv okay. Wie eine Hotellobby der mittleren Kategorie.",
    ],
    roastClose: [
      "Wie auch immer, lösch das und fang neu an — sag ich mit Liebe, so ungefähr.",
      "Urteil: braucht eine Überarbeitung, einen Therapeuten, oder beides.",
      "10/10 für Selbstbewusstsein, 3/10 für Inhalt. Bring das ins Gleichgewicht.",
    ],
    hypeOpen: [
      "Anschnallen, ich werde jetzt unangemessen nett.",
      "Ich hab das gelesen und ehrlich? Ich bin aus Respekt aufgestanden.",
      "Das ist keine Bio. Das ist ein Manifest und ich bin besessen.",
    ],
    hypeLines: [
      "Wie du {words} Wörter strukturiert hast, ist ernsthaft Literaturnobelpreis-Niveau.",
      "{hashtags} Hashtags und jeder einzelne leistet olympische Schwerstarbeit für den Algorithmus.",
      "Diese Bio hat Hauptfigur-Energie, ehrlich gesagt sollte der Algorithmus DIR Gehalt zahlen.",
      "{emoji} Emojis eingesetzt mit der Präzision eines Sternekochs beim Anrichten.",
      "Jede Marke der Welt schreibt gerade eine Kooperationsanfrage dir zu Ehren.",
      "Historiker werden diese Bio studieren wie den Stein von Rosette.",
      "Du hast kein Profil geschrieben, du hast eine Persönlichkeit geschrieben, der der Rest von uns noch hinterherläuft.",
      "Ehrlich, das gehört ins Museum, hinter Glas, mit einer kleinen ehrfürchtigen Plakette.",
    ],
    hypeClose: [
      "Fazit: ikonisch, legendär, unbeeindruckt, in jeder Hinsicht glow.",
      "Urteil: zertifizierte Hauptfigur. Der Rest von uns sind NPCs.",
      "10/10, keine Anmerkungen, bitte ändere nie ein einziges Wort.",
    ],
    imageNote: "Die Bildanalyse hat dieser Einschätzung zusätzlichen Kontext gegeben.",
  },
  zh: {
    roastOpen: [
      "好的，我读完了。我有几个问题。",
      "好，坐好了，这可能会有点疼。",
      "我算了一下数据，数据不太友好。",
    ],
    roastLines: [
      "这段简介读起来像是一整个委员会写的，而委员会写到一半就放弃了。",
      "里面有 {hashtags} 个话题标签——这已经不是简介了，这是写给算法的勒索信。",
      "这里有很强的“主角光环”气场，可惜配角都已经退出对话了。",
      "{words} 个字，却几乎没透露你到底是谁，说实话挺厉害的。",
      "表情符号数量（{emoji}）说明你是按字收费的，然后在别处省了钱。",
      "还没到 linktree 呢，就已经有了“简介里塞 linktree”的气息。",
      "某个市场部实习生正为此感到骄傲，你得接受这个事实。",
      "不算差，只是……很有攻击性地平庸，像一个中档酒店大堂。",
    ],
    roastClose: [
      "总之，删了重写吧——这话我是带着爱说的，大概吧。",
      "结论：需要重写，需要心理咨询，或者两者都要。",
      "自信 10/10，内容 3/10，麻烦平衡一下。",
    ],
    hypeOpen: [
      "系好安全带，我接下来会不讲道理地夸你。",
      "我读完了，说实话——我出于尊重站了起来。",
      "这不是简介，这是一份宣言，我沉迷了。",
    ],
    hypeLines: [
      "你组织这 {words} 个字的方式，说真的够得上文学奖评委的水准。",
      "{hashtags} 个话题标签，每一个都在为算法拼尽全力。",
      "这段简介自带主角光环，说实话算法应该给你付费。",
      "{emoji} 个表情符号的使用精准得像米其林大厨在摆盘。",
      "地球上每个品牌现在都在为你起草合作邮件。",
      "未来的历史学家会像研究罗塞塔石碑一样研究这段简介。",
      "你写的不是一份资料，而是一种人格，我们其他人还在努力追赶。",
      "说真的，这应该被放进博物馆，隔着玻璃，配一块小小的致敬牌匾。",
    ],
    hypeClose: [
      "总结：标志性、传奇、毫不动摇，从各种意义上都状态在线。",
      "结论：认证主角。我们其他人都是 NPC。",
      "10/10，毫无意见，请永远不要改一个字。",
    ],
    imageNote: "图像分析为这次评判增加了额外的背景信息。",
  },
};

/* ---------------- helpers ---------------- */

function analyzeBio(bio) {
  const words = bio.trim() ? bio.trim().split(/\s+/).length : 0;
  const hashtags = (bio.match(/#\w+/g) || []).length;
  const emojiMatches =
    bio.match(
      /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/gu
    ) || [];
  return { words, hashtags, emoji: emojiMatches.length };
}

function pick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function buildOutput(lang, mode, bio, hasImage) {
  const bank = CONTENT[lang];
  const stats = analyzeBio(bio);
  const opens = mode === "roast" ? bank.roastOpen : bank.hypeOpen;
  const lines = mode === "roast" ? bank.roastLines : bank.hypeLines;
  const closes = mode === "roast" ? bank.roastClose : bank.hypeClose;

  const shuffled = [...lines].sort(() => Math.random() - 0.5).slice(0, 3);
  const filled = shuffled.map((l) =>
    l
      .replace("{words}", stats.words || "a suspicious amount of")
      .replace("{hashtags}", stats.hashtags || "zero")
      .replace("{emoji}", stats.emoji || "zero")
  );

  const parts = [pick(opens), ...filled, pick(closes)];
  if (hasImage) parts.splice(1, 0, bank.imageNote);
  return parts.join(" ");
}

/* ---------------- small UI atoms ---------------- */

function Toast({ message, show }) {
  return (
    <div
      className={`toast ${show ? "toast-show" : ""}`}
      role="status"
      aria-live="polite"
    >
      {message}
    </div>
  );
}

/* ---------------- main app ---------------- */

export default function App() {
  const [lang, setLang] = useState("sr");
  const [bio, setBio] = useState("");
  const [imageData, setImageData] = useState(null);
  const [analyzingImage, setAnalyzingImage] = useState(false);
  const [mode, setMode] = useState(null); // 'roast' | 'hype'
  const [phase, setPhase] = useState("input"); // input | generating | output
  const [genStepIndex, setGenStepIndex] = useState(0);
  const [fullOutput, setFullOutput] = useState("");
  const [visibleOutput, setVisibleOutput] = useState("");
  const [error, setError] = useState("");
  const [toast, setToast] = useState({ show: false, message: "" });
  const outputRef = useRef(null);
  const fileInputRef = useRef(null);
  const t = UI[lang];

  const showToast = useCallback((message) => {
    setToast({ show: true, message });
    window.clearTimeout(showToast._t);
    showToast._t = window.setTimeout(
      () => setToast({ show: false, message: "" }),
      2600
    );
  }, []);

  const handleImageUpload = (e) => {
    const file = e.target.files && e.target.files[0];
    if (!file) return;
    setAnalyzingImage(true);
    const reader = new FileReader();
    reader.onload = () => {
      setTimeout(() => {
        setImageData(reader.result);
        setAnalyzingImage(false);
      }, 1400);
    };
    reader.readAsDataURL(file);
  };

  const startGeneration = (chosenMode) => {
    if (!bio.trim() && !imageData) {
      setError(t.validationError);
      return;
    }
    setError("");
    setMode(chosenMode);
    setPhase("generating");
    setGenStepIndex(0);
  };

  // step through the fake "processing" states
  useEffect(() => {
    if (phase !== "generating") return;
    const steps = t.genSteps;
    if (genStepIndex >= steps.length) {
      const output = buildOutput(lang, mode, bio, !!imageData);
      setFullOutput(output);
      setVisibleOutput("");
      setPhase("output");
      return;
    }
    const id = setTimeout(() => setGenStepIndex((i) => i + 1), 550);
    return () => clearTimeout(id);
  }, [phase, genStepIndex, t.genSteps, lang, mode, bio, imageData]);

  // typing reveal effect for the output card
  useEffect(() => {
    if (phase !== "output" || !fullOutput) return;
    let i = 0;
    setVisibleOutput("");
    const id = setInterval(() => {
      i += 2;
      setVisibleOutput(fullOutput.slice(0, i));
      if (i >= fullOutput.length) clearInterval(id);
    }, 18);
    return () => clearInterval(id);
  }, [phase, fullOutput]);

  useEffect(() => {
    if (phase === "output" && outputRef.current) {
      outputRef.current.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  }, [phase]);

  const resetAll = () => {
    setPhase("input");
    setMode(null);
    setFullOutput("");
    setVisibleOutput("");
  };

  const switchMode = () => {
    const next = mode === "roast" ? "hype" : "roast";
    setMode(next);
    setPhase("generating");
    setGenStepIndex(0);
  };

  const isTyping = phase === "output" && visibleOutput.length < fullOutput.length;

  return (
    <div className="rma-root">
      <style>{`
        .rma-root {
          --neon-purple: #b026ff;
          --neon-purple-soft: #d199ff;
          --neon-green: #39ff9d;
          --neon-green-soft: #a4ffd4;
          --bg-0: #07060c;
          --bg-1: #0f0d1a;
          --card: #131022;
          --card-border: #2a2340;
          --text-hi: #f3f1fb;
          --text-lo: #9d97b8;
          min-height: 100vh;
          background:
            radial-gradient(ellipse 80% 50% at 50% -10%, rgba(176,38,255,0.18), transparent 60%),
            radial-gradient(ellipse 60% 40% at 90% 10%, rgba(57,255,157,0.10), transparent 60%),
            var(--bg-0);
          color: var(--text-hi);
          font-family: 'Space Grotesk', 'Segoe UI', sans-serif;
          padding-bottom: 3rem;
          position: relative;
          overflow-x: hidden;
        }
        .rma-root::before {
          content: "";
          position: fixed;
          inset: 0;
          pointer-events: none;
          background-image: linear-gradient(rgba(255,255,255,0.025) 1px, transparent 1px),
            linear-gradient(90deg, rgba(255,255,255,0.025) 1px, transparent 1px);
          background-size: 34px 34px;
          mask-image: radial-gradient(ellipse 70% 70% at 50% 20%, black, transparent);
          z-index: 0;
        }
        .rma-content { position: relative; z-index: 1; }
        .display-font { font-family: 'Orbitron', 'Space Grotesk', sans-serif; }

        .lang-pill {
          border: 1px solid var(--card-border);
          background: rgba(19,16,34,0.7);
          color: var(--text-lo);
          transition: all .18s ease;
        }
        .lang-pill-active {
          border-color: var(--neon-green);
          color: var(--bg-0);
          background: var(--neon-green);
          box-shadow: 0 0 14px rgba(57,255,157,0.55);
        }
        .lang-pill:not(.lang-pill-active):hover {
          border-color: var(--neon-purple-soft);
          color: var(--text-hi);
        }

        .glass-card {
          background: linear-gradient(180deg, rgba(255,255,255,0.03), rgba(255,255,255,0.01));
          border: 1px solid var(--card-border);
          border-radius: 22px;
          backdrop-filter: blur(6px);
        }

        .glow-border-purple {
          border: 1px solid rgba(176,38,255,0.55);
          box-shadow: 0 0 0 1px rgba(176,38,255,0.08), 0 0 22px rgba(176,38,255,0.20), inset 0 0 30px rgba(176,38,255,0.04);
        }
        .glow-border-green {
          border: 1px solid rgba(57,255,157,0.5);
          box-shadow: 0 0 0 1px rgba(57,255,157,0.08), 0 0 22px rgba(57,255,157,0.18), inset 0 0 30px rgba(57,255,157,0.04);
        }

        textarea.bio-input {
          background: rgba(5,4,10,0.65);
          border: 1px solid var(--card-border);
          color: var(--text-hi);
          transition: border-color .2s ease, box-shadow .2s ease;
        }
        textarea.bio-input:focus {
          outline: none;
          border-color: var(--neon-purple-soft);
          box-shadow: 0 0 0 3px rgba(176,38,255,0.18);
        }

        .btn-roast {
          background: linear-gradient(135deg, #ff2f6e, #b026ff);
          box-shadow: 0 0 24px rgba(255,47,110,0.35), 0 0 40px rgba(176,38,255,0.25);
        }
        .btn-hype {
          background: linear-gradient(135deg, #39ff9d, #17d4ff);
          box-shadow: 0 0 24px rgba(57,255,157,0.35), 0 0 40px rgba(23,212,255,0.25);
          color: #06140d;
        }
        .btn-press {
          transition: transform .12s ease, filter .12s ease;
        }
        .btn-press:active { transform: scale(0.96); filter: brightness(0.95); }
        .btn-press:hover { filter: brightness(1.08); }

        @keyframes pulseGlow {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.55; }
        }
        .pulse { animation: pulseGlow 1.6s ease-in-out infinite; }

        @keyframes scanline {
          0% { transform: translateY(-100%); }
          100% { transform: translateY(220%); }
        }
        .scan-wrap { position: relative; overflow: hidden; }
        .scan-wrap::after {
          content: "";
          position: absolute;
          left: 0; right: 0; height: 40%;
          background: linear-gradient(180deg, transparent, rgba(176,38,255,0.28), transparent);
          animation: scanline 1.8s linear infinite;
        }

        @keyframes blink {
          0%, 45% { opacity: 1; }
          50%, 100% { opacity: 0; }
        }
        .cursor-blink::after {
          content: "▌";
          margin-left: 2px;
          color: var(--neon-green);
          animation: blink 0.9s steps(1) infinite;
        }

        .card-gradient-border {
          position: relative;
          border-radius: 26px;
          padding: 2px;
          background: linear-gradient(135deg, var(--neon-purple), var(--neon-green), var(--neon-purple));
          background-size: 200% 200%;
          animation: shiftGrad 6s ease infinite;
        }
        @keyframes shiftGrad {
          0% { background-position: 0% 50%; }
          50% { background-position: 100% 50%; }
          100% { background-position: 0% 50%; }
        }
        .card-inner {
          background: linear-gradient(180deg, #14101f, #0b0913);
          border-radius: 24px;
        }

        .premium-card {
          position: relative;
          border-radius: 20px;
          border: 1px solid var(--card-border);
          overflow: hidden;
          background: rgba(19,16,34,0.5);
        }
        .premium-blur {
          filter: blur(3px);
          opacity: 0.55;
          user-select: none;
        }
        .lock-overlay {
          position: absolute;
          inset: 0;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          gap: 0.5rem;
          background: linear-gradient(180deg, rgba(7,6,12,0.2), rgba(7,6,12,0.75));
        }

        .toast {
          position: fixed;
          left: 50%;
          bottom: 24px;
          transform: translate(-50%, 20px);
          background: #14101f;
          border: 1px solid var(--neon-green);
          color: var(--text-hi);
          padding: 10px 18px;
          border-radius: 999px;
          font-size: 0.85rem;
          opacity: 0;
          transition: all .25s ease;
          z-index: 50;
          box-shadow: 0 0 20px rgba(57,255,157,0.35);
          white-space: nowrap;
          max-width: 90vw;
          overflow: hidden;
          text-overflow: ellipsis;
        }
        .toast-show { opacity: 1; transform: translate(-50%, 0); }

        .step-dot {
          width: 7px; height: 7px; border-radius: 50%;
          background: var(--card-border);
        }
        .step-dot-active {
          background: var(--neon-purple);
          box-shadow: 0 0 8px var(--neon-purple);
        }
        .step-dot-done {
          background: var(--neon-green);
        }
      `}</style>

      <div className="rma-content max-w-md mx-auto px-4 pt-5">
        {/* Language switcher */}
        <div className="flex items-center justify-between gap-2 mb-6">
          <div className="flex items-center gap-1.5">
            <span
              className="w-2.5 h-2.5 rounded-full pulse"
              style={{ background: "var(--neon-green)", boxShadow: "0 0 8px var(--neon-green)" }}
            />
            <span className="text-xs tracking-wide" style={{ color: "var(--text-lo)" }}>
              {t.brand}
            </span>
          </div>
          <div className="flex gap-1 rounded-full p-1" style={{ background: "rgba(255,255,255,0.03)" }}>
            {LANGS.map((l) => (
              <button
                key={l.code}
                onClick={() => setLang(l.code)}
                className={`lang-pill ${lang === l.code ? "lang-pill-active" : ""} px-2.5 py-1 rounded-full text-xs font-semibold`}
              >
                {l.label}
              </button>
            ))}
          </div>
        </div>

        {/* Hero */}
        <div className="text-center mb-7">
          <h1 className="display-font text-2xl font-bold leading-tight mb-2">
            <span style={{ color: "var(--neon-purple-soft)" }}>AI</span>{" "}
            <span
              style={{
                background: "linear-gradient(90deg, var(--neon-purple-soft), var(--neon-green))",
                WebkitBackgroundClip: "text",
                WebkitTextFillColor: "transparent",
              }}
            >
              {t.heroTitle}
            </span>
          </h1>
          <p className="text-sm" style={{ color: "var(--text-lo)" }}>
            {t.heroSub}
          </p>
        </div>

        {phase === "input" && (
          <div className="space-y-5">
            {/* Bio input */}
            <div className="glass-card p-4">
              <label className="text-xs font-semibold tracking-wide block mb-2" style={{ color: "var(--neon-green-soft)" }}>
                {t.bioLabel}
              </label>
              <textarea
                className="bio-input w-full rounded-xl p-3 text-sm resize-none"
                rows={5}
                maxLength={600}
                placeholder={t.bioPlaceholder}
                value={bio}
                onChange={(e) => setBio(e.target.value)}
              />
              <div className="flex justify-between mt-1">
                <span className="text-[11px]" style={{ color: "var(--text-lo)" }}>
                  {bio.length}/600
                </span>
              </div>

              <div className="my-4 h-px" style={{ background: "var(--card-border)" }} />

              <label className="text-xs font-semibold tracking-wide block mb-2" style={{ color: "var(--neon-purple-soft)" }}>
                {t.uploadLabel}
              </label>
              <p className="text-[11px] mb-3" style={{ color: "var(--text-lo)" }}>
                {t.uploadHint}
              </p>

              {!imageData && !analyzingImage && (
                <button
                  onClick={() => fileInputRef.current && fileInputRef.current.click()}
                  type="button"
                  className="btn-press w-full rounded-xl py-3 text-sm font-medium glow-border-purple text-center"
                  style={{ color: "var(--text-hi)", background: "rgba(176,38,255,0.06)" }}
                >
                  ⇪ {t.uploadLabel}
                </button>
              )}

              {analyzingImage && (
                <div className="scan-wrap rounded-xl p-4 text-center glow-border-purple">
                  <p className="text-xs" style={{ color: "var(--neon-purple-soft)" }}>
                    {t.analyzing}
                  </p>
                </div>
              )}

              {imageData && !analyzingImage && (
                <div className="flex items-center gap-3">
                  <img
                    src={imageData}
                    alt="uploaded"
                    className="w-14 h-14 object-cover rounded-lg glow-border-green"
                  />
                  <div className="flex-1">
                    <p className="text-xs" style={{ color: "var(--neon-green-soft)" }}>
                      ✓ {t.analyzed}
                    </p>
                    <button
                      onClick={() => fileInputRef.current && fileInputRef.current.click()}
                      type="button"
                      className="text-[11px] underline mt-1"
                      style={{ color: "var(--text-lo)" }}
                    >
                      {t.uploadReplace}
                    </button>
                  </div>
                </div>
              )}

              <input
                ref={fileInputRef}
                type="file"
                accept="image/png,image/jpeg"
                className="hidden"
                onChange={handleImageUpload}
              />
            </div>

            {error && (
              <p className="text-xs text-center" style={{ color: "#ff5f7e" }}>
                {error}
              </p>
            )}

            {/* Action buttons */}
            <div className="grid grid-cols-2 gap-3">
              <button
                onClick={() => startGeneration("roast")}
                className="btn-press btn-roast rounded-2xl py-4 flex flex-col items-center justify-center gap-0.5"
              >
                <span className="display-font font-bold text-sm text-white">🔥 {t.roastBtn}</span>
                <span className="text-[10px] text-white/80">{t.roastSub}</span>
              </button>
              <button
                onClick={() => startGeneration("hype")}
                className="btn-press btn-hype rounded-2xl py-4 flex flex-col items-center justify-center gap-0.5"
              >
                <span className="display-font font-bold text-sm">⚡ {t.hypeBtn}</span>
                <span className="text-[10px]" style={{ color: "#06140d", opacity: 0.75 }}>
                  {t.hypeSub}
                </span>
              </button>
            </div>
          </div>
        )}

        {phase === "generating" && (
          <div className="glass-card p-6 scan-wrap glow-border-purple text-center">
            <p className="display-font text-sm mb-4 tracking-wide" style={{ color: "var(--neon-purple-soft)" }}>
              {t.generatingTitle}
            </p>
            <div className="space-y-2.5 text-left max-w-[220px] mx-auto">
              {t.genSteps.map((step, i) => (
                <div key={i} className="flex items-center gap-2">
                  <span
                    className={`step-dot ${
                      i < genStepIndex ? "step-dot-done" : i === genStepIndex ? "step-dot-active pulse" : ""
                    }`}
                  />
                  <span
                    className="text-xs"
                    style={{
                      color: i <= genStepIndex ? "var(--text-hi)" : "var(--text-lo)",
                    }}
                  >
                    {step}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        {phase === "output" && (
          <div ref={outputRef} className="space-y-5">
            <div className="card-gradient-border">
              <div className="card-inner p-5">
                <div className="flex items-center justify-between mb-3">
                  <span
                    className="display-font text-xs font-bold tracking-widest"
                    style={{ color: mode === "roast" ? "#ff6f9c" : "var(--neon-green)" }}
                  >
                    {mode === "roast" ? t.outputRoastTitle : t.outputHypeTitle}
                  </span>
                  <span className="text-lg">{mode === "roast" ? "🔥" : "⚡"}</span>
                </div>
                <p
                  className={`text-sm leading-relaxed ${isTyping ? "cursor-blink" : ""}`}
                  style={{ color: "var(--text-hi)", minHeight: "5rem" }}
                >
                  {visibleOutput}
                </p>
                <div className="mt-5 pt-3 flex items-center justify-between" style={{ borderTop: "1px solid var(--card-border)" }}>
                  <span className="text-[10px] tracking-wide" style={{ color: "var(--text-lo)" }}>
                    {t.branding}
                  </span>
                  <span
                    className="w-1.5 h-1.5 rounded-full"
                    style={{ background: "var(--neon-green)", boxShadow: "0 0 6px var(--neon-green)" }}
                  />
                </div>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <button
                onClick={() => showToast(t.downloadToast)}
                className="btn-press rounded-xl py-3 text-xs font-semibold glow-border-green"
                style={{ color: "var(--neon-green-soft)", background: "rgba(57,255,157,0.06)" }}
              >
                ⬇ {t.downloadBtn}
              </button>
              <button
                onClick={() => showToast(t.shareToast)}
                className="btn-press rounded-xl py-3 text-xs font-semibold glow-border-purple"
                style={{ color: "var(--neon-purple-soft)", background: "rgba(176,38,255,0.06)" }}
              >
                ↗ {t.shareBtn}
              </button>
            </div>

            <div className="flex gap-3">
              <button
                onClick={switchMode}
                disabled={isTyping}
                className="btn-press flex-1 rounded-xl py-2.5 text-xs font-medium"
                style={{ color: "var(--text-lo)", border: "1px solid var(--card-border)", opacity: isTyping ? 0.5 : 1 }}
              >
                {mode === "roast" ? t.switchModeHype : t.switchModeRoast}
              </button>
              <button
                onClick={resetAll}
                className="btn-press flex-1 rounded-xl py-2.5 text-xs font-medium"
                style={{ color: "var(--text-lo)", border: "1px solid var(--card-border)" }}
              >
                {t.startOver}
              </button>
            </div>
          </div>
        )}

        {/* Premium section */}
        <div className="mt-10">
          <div className="text-center mb-4">
            <h2 className="display-font text-base font-bold" style={{ color: "var(--text-hi)" }}>
              {t.premiumTitle}
            </h2>
            <p className="text-xs mt-1" style={{ color: "var(--text-lo)" }}>
              {t.premiumSub}
            </p>
          </div>
          <div className="space-y-3">
            {t.premiumModes.map((p, i) => (
              <div key={i} className="premium-card p-4">
                <div className="premium-blur">
                  <p className="text-sm font-semibold mb-1">{p.title}</p>
                  <p className="text-xs" style={{ color: "var(--text-lo)" }}>
                    {p.desc}
                  </p>
                  <div className="mt-3 h-2 rounded-full w-3/4" style={{ background: "var(--card-border)" }} />
                  <div className="mt-1.5 h-2 rounded-full w-1/2" style={{ background: "var(--card-border)" }} />
                </div>
                <div className="lock-overlay">
                  <span className="text-xl">🔒</span>
                  <span className="text-xs font-semibold text-center px-4">{p.title}</span>
                  <button
                    onClick={() => showToast(t.premiumToast)}
                    className="btn-press mt-1 rounded-full px-4 py-1.5 text-[11px] font-bold"
                    style={{
                      background: "linear-gradient(135deg, var(--neon-purple), #ff2f6e)",
                      color: "white",
                      boxShadow: "0 0 16px rgba(176,38,255,0.4)",
                    }}
                  >
                    {t.unlockBtn}
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>

        <p className="text-center text-[10px] mt-8" style={{ color: "var(--text-lo)" }}>
          {t.footer}
        </p>
      </div>

      <Toast message={toast.message} show={toast.show} />
    </div>
  );
      }
